### ISSUE TITLE
Designs Crash on Import

### ISSUE THREAD

**Issue by nickfong** [cadnano/cadnano2.5#167]
On `abstract-view-engine`, importing a design crashes the app

```
Traceback (most recent call last):
  File "./cadnano/views/sliceview/nucleicacidpartitem.py", line 245, in partRemovedSlot
    return self.destroyItem()
  File "./cadnano/views/sliceview/nucleicacidpartitem.py", line 273, in destroyItem
    self.griditem.destroyItem()
AttributeError: 'GridItem' object has no attribute 'destroyItem'
Abort trap: 6
```

**Comment by nickfong** [comment]
Changes being made on the `nickfong:import-fix` branch
