### ISSUE TITLE
SPA Mode Doesn't Work

### ISSUE THREAD

**Issue by nickfong** [cadnano/cadnano2.5#169]
On `abstract-view-engine`, attempting to add VHs via the shortest-path-add mode causes a crash.  
```
Traceback (most recent call last):
  File "./cadnano/views/sliceview/griditem.py", line 622, in mousePressEvent
    return self.parent_obj.mousePressEvent(event)
  File "./cadnano/views/sliceview/griditem.py", line 425, in mousePressEvent
    getattr(self, tool_method_name)(tool, part_item, event)
  File "./cadnano/views/sliceview/griditem.py", line 538, in createToolMousePress
    part_item.createToolMousePress(tool, event, alt_event)
  File "./cadnano/views/sliceview/nucleicacidpartitem.py", line 856, in createToolMousePress
    is_spa_mode=is_spa_mode)
  File "./cadnano/views/sliceview/nucleicacidpartitem.py", line 911, in _handleShortestPathMousePress
    last_vhi_id = self.createToolShortestPath(tool=tool, start=self.shortest_path_start, end=position)
  File "./cadnano/views/sliceview/nucleicacidpartitem.py", line 972, in createToolShortestPath
    parity=parity_list)
TypeError: batchCreateVirtualHelices() got an unexpected keyword argument 'parity'
Abort trap: 6
```

**Comment by nickfong** [comment]
Changes are being made on the `nickfong/cadnano2.5/spa-fix` branch

**Comment by grinner** [comment]
fixed and merged
