### ISSUE TITLE
Saving cadnano 2 file corrupts it

### ISSUE THREAD

**Issue by mmguar** [cadnano/cadnano2.5#187]
I am working on a cadnano 2 file and any change (or no change), followed by a save in cadnano in 2.5, will corrupt the file making it unreadable by both cadnano 2 and cadnano 2.5.
Cadnano 2.5 will open it but the path view will be completely empty and only show the (correct) number of helices in the slice view.

Additionally: delete does not seem to work (signaled by another user on gitter) and opening a json when another one is open throws exception:
```
Traceback (most recent call last):
  File "/home/matteo/.local/lib/python3.9/site-packages/cadnano/views/pathview/strand/stranditem.py", line 153, in strandRemovedSlot
    self.destroyItem()
  File "/home/matteo/.local/lib/python3.9/site-packages/cadnano/views/pathview/strand/stranditem.py", line 170, in destroyItem
    insertionItem.remove()
AttributeError: 'InsertionItem' object has no attribute 'remove'
Aborted (core dumped)
```
While I know this is just one bug, the additional issue might make clear to you what is wrong in my installation. I will open other Issues otherwise.

Cadnano 2.5.2 from github on python 3.9.2 on linux

**Comment by mmguar** [comment]
I understand now this is issue #182
