### ISSUE TITLE
Argument 1 has unexpected type 'str'

### ISSUE THREAD

**Issue by HalseyWang** [cadnano/cadnano2.5#190]
How to solve this problem, Thanks

(https://user-images.githubusercontent.com/70701919/146668987-2f76b9cb-4516-4ca1-bc3e-4ac70dd04baf.jpg)

**C:\Users\wangy>cadnano
Traceback (most recent call last):
  File "C:\Users\wangy\AppData\Local\Programs\Python\Python39\Scripts\cadnano-script.py", line 33, in <module>
    sys.exit(load_entry_point('cadnano==2.5.2.1', 'console_scripts', 'cadnano')())
  File "C:\Users\wangy\AppData\Local\Programs\Python\Python39\lib\site-packages\cadnano\bin\main.py", line 36, in main
    app = initAppWithGui(argv, do_exec=False)
  File "C:\Users\wangy\AppData\Local\Programs\Python\Python39\lib\site-packages\cadnano\__init__.py", line 62, in initAppWithGui
    shared_app = CadnanoQt(app_args)
  File "C:\Users\wangy\AppData\Local\Programs\Python\Python39\lib\site-packages\cadnano\cadnanoqt.py", line 83, in __init__
    self.prefs = Preferences()
  File "C:\Users\wangy\AppData\Local\Programs\Python\Python39\lib\site-packages\cadnano\views\preferences.py", line 39, in __init__
    self.readPreferences()
  File "C:\Users\wangy\AppData\Local\Programs\Python\Python39\lib\site-packages\cadnano\views\preferences.py", line 76, in readPreferences
    ui_prefs.show_icon_labels.setChecked(self.show_icon_labels)
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'**

**Comment by Skcolreh** [comment]
lib\site-packages\cadnano\views\preferences.py
self.ui_prefs.show_icon_labels.setChecked(self.show_icon_labels == 'true')
