### ISSUE TITLE
cadnano not running after pip3 install

### ISSUE THREAD

**Issue by kebron1** [cadnano/cadnano2.5#192]
Python version 3.9.7
OS Windows 11
Installed through Jupyter terminal
Installation goes fine but when trying to run "cadnano" from command line, returns error:

"Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\cadnano-script.py", line 33, in <module>
    sys.exit(load_entry_point('cadnano==2.5.2.1', 'console_scripts', 'cadnano')())
  File "C:\ProgramData\Anaconda3\lib\site-packages\cadnano\bin\main.py", line 36, in main
    app = initAppWithGui(argv, do_exec=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cadnano\__init__.py", line 60, in initAppWithGui
    from cadnano.cadnanoqt import CadnanoQt
  File "C:\ProgramData\Anaconda3\lib\site-packages\cadnano\cadnanoqt.py", line 21, in <module>
    from PyQt5.QtCore import (
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found."

**Comment by blackwellbert** [comment]
I am having a similar issue on Windows 10.  I can only run version 2.4.7 not 2.5.
