### ISSUE TITLE
cadnano2.5 not running on Windows 10 after installation

### ISSUE THREAD

**Issue by blackwellbert** [cadnano/cadnano2.5#194]
After installing according to instructions and using the command "cadnano" in dos shell from cadnano2.5 directory, I get the following output:

C:\Users\pparr\OneDrive\Documents\GitHub\cadnano2.5>cadnano
Traceback (most recent call last):
  File "C:\Users\pparr\AppData\Local\Programs\Python\Python310\Scripts\cadnano-script.py", line 33, in <module>
    sys.exit(load_entry_point('cadnano==2.5.2.1', 'console_scripts', 'cadnano')())
  File "C:\Users\pparr\AppData\Local\Programs\Python\Python310\lib\site-packages\cadnano\bin\main.py", line 36, in main
    app = initAppWithGui(argv, do_exec=False)
  File "C:\Users\pparr\AppData\Local\Programs\Python\Python310\lib\site-packages\cadnano\__init__.py", line 65, in initAppWithGui
    shared_app.finishInit()
  File "C:\Users\pparr\AppData\Local\Programs\Python\Python310\lib\site-packages\cadnano\cadnanoqt.py", line 103, in finishInit
    from cadnano.document import Document
  File "C:\Users\pparr\AppData\Local\Programs\Python\Python310\lib\site-packages\cadnano\document.py", line 38, in <module>
    from cadnano.fileio.decode import decodeFile
  File "C:\Users\pparr\AppData\Local\Programs\Python\Python310\lib\site-packages\cadnano\fileio\decode.py", line 6, in <module>
    import cadnano.fileio.v2decode as v2decode
  File "C:\Users\pparr\AppData\Local\Programs\Python\Python310\lib\site-packages\cadnano\fileio\v2decode.py", line 18, in <module>
    from cadnano.part.nucleicacidpart import DEFAULT_RADIUS
  File "C:\Users\pparr\AppData\Local\Programs\Python\Python310\lib\site-packages\cadnano\part\nucleicacidpart.py", line 40, in <module>
    from cadnano.strandset import SplitCommand, StrandSet
  File "C:\Users\pparr\AppData\Local\Programs\Python\Python310\lib\site-packages\cadnano\strandset\__init__.py", line 1, in <module>
    from .strandset import *
  File "C:\Users\pparr\AppData\Local\Programs\Python\Python310\lib\site-packages\cadnano\strandset\strandset.py", line 22, in <module>
    from .removestrandcmd import RemoveStrandCommand
  File "C:\Users\pparr\AppData\Local\Programs\Python\Python310\lib\site-packages\cadnano\strandset\removestrandcmd.py", line 4, in <module>
    from cadnano.views.pathview import pathstyles
  File "C:\Users\pparr\AppData\Local\Programs\Python\Python310\lib\site-packages\cadnano\views\pathview\pathstyles.py", line 178, in <module>
    XOVER_LABEL_FONT = QFont(THE_FONT, THE_FONT_SIZE/2, QFont.Light)
TypeError: arguments did not match any overloaded call:
  QFont(): too many arguments
  QFont(str, pointSize: int = -1, weight: int = -1, italic: bool = False): argument 2 has unexpected type 'float'
  QFont(QFont, QPaintDevice): argument 1 has unexpected type 'str'
  QFont(QFont): argument 1 has unexpected type 'str'
  QFont(Any): too many arguments

However, when I run the command "cadnano2' from the same directory, cadnano2.4 runs.  So why does the 2.4 version run but not the 2.5 version as shown by the errors above?  Or am I missing something?

Thanks in advance for your help!

![image](https://user-images.githubusercontent.com/43821314/180571831-0bb07acb-a258-4af0-97f6-e22a6a681ca7.png)

**Comment by sdouglas** [comment]
In general, we probably need to start working on porting cadnano2.5 over to PyQt6. 

In the meantime, I think this particular bug can be fixed by casting the QFont parameter as an `int` — I saw similar behavior with cadnano2.

I’ll try to take a look within the next week or so.

**Comment by blackwellbert** [comment]
Thanks for your email!  Is it possible to use “autobreak”?  If so, how do I
activate it?

**Comment by sdouglas** [comment]
The old algorithm did not select very good break positions, so we removed it to encourage users to break staples manually. Our lab has been building a new algorithm that gives even better results, based on applying a global optimization to minimize scaffold looping entropy. This is not yet published, but I hope to launch it as a web-based tool in the coming months, where you will be able to upload cadnano files and apply the algorithm to perform a highly optimized autobreak. 

In the meantime, I recommend breaking manually using the the "Rule 3" heuristic from this paper:
[https://www.nature.com/articles/ncomms2095](https://urldefense.com/v3/__https://www.nature.com/articles/ncomms2095__;!!LQC6Cpwp!uqCLewq1BCo3sVhAqVMNigJIV4ribrsWgGlFNmNRj55qNEoGGtN7IyN5N-mUXmkY3F307wCPmC8L2p6qAa7p9uJY64mVwmdD5P1ay9IS_A$)

**Comment by blackwellbert** [comment]
Thanks for the info!  I will check it out!

**Comment by RodenLuo** [comment]
Any news about the AutoBreak? Either in Cadnano or the web-based tool? Thanks.
