### ISSUE TITLE
'strandset_idx' is not defined in strandset.removeStrand

### ISSUE THREAD

**Issue by sdouglas** [cadnano/cadnano2.5#32]
Selected 2 scaf strands and pressed "delete" key gave this exception
```
Traceback (most recent call last):
  File "./cadnano/gui/views/pathview/pathselection.py", line 136, in keyPressEvent
    self.selectionbox.deleteSelection()
  File "./cadnano/gui/views/pathview/pathselection.py", line 470, in deleteSelection
    self._item_group.document().deleteSelection()
  File "./cadnano/document.py", line 341, in deleteSelection
    strand.strandSet().removeStrand(strand)
  File "./cadnano/strandset/strandset.py", line 317, in removeStrand
    return strandset_idx
NameError: name 'strandset_idx' is not defined
```

(Maybe this is fixed elsewhere but I'm working in outlinerdev branch)

**Comment by grinner** [comment]
fixed in b58d5920ee9d52d741ab5b7f77af5e37402644be
