### ISSUE TITLE
autoscaf bug

### ISSUE THREAD

**Issue by sdouglas** [cadnano/cadnano2.5#33]
Randomly clicking around on some stacked parts and saw this (noting here, but not sure how to reproduce)
```
Traceback (most recent call last):
  File "./cadnano/gui/views/sliceview/emptyhelixitem.py", line 328, in mouseReleaseEvent
    self.autoScafMidSeam(strands)
  File "./cadnano/gui/views/sliceview/emptyhelixitem.py", line 182, in autoScafMidSeam
    strand2 = vh2.scaffoldStrandSet().getStrand(ss_base_low_idx2)
AttributeError: 'NoneType' object has no attribute 'scaffoldStrandSet'
```

**Comment by grinner** [comment]
what branch?
