### ISSUE TITLE
Deleting a strand produces Error/Traceback

### ISSUE THREAD

**Issue by scholer** [cadnano/cadnano2.5#35]
In current dev (and outlinerdev) branches, invoking StrandSet.removeStrand() - e.g. by marking a strand in the GUI and pressing delete - produces a NameError and traceback in the terminal:
Traceback (most recent call last):
  File ".\cadnano\gui\views\pathview\pathselection.py", line 135, in keyPressEvent
    self.selectionbox.deleteSelection()
  File ".\cadnano\gui\views\pathview\pathselection.py", line 469, in deleteSelection
    self._item_group.document().deleteSelection()
  File ".\cadnano\document.py", line 348, in deleteSelection
    strand.strandSet().removeStrand(strand)
  File ".\cadnano\strandset\strandset.py", line 322, in removeStrand
    return strandset_idx
NameError: name 'strandset_idx' is not defined

**Comment by grinner** [comment]
This was legacy from the old implementation.  This is why I need to write tests.  Anyway, I went in and manually fixed things because I didn't like 100% of the formatting changes, but please re submit a PR for the docstring changes from bf0d028
