### ISSUE TITLE
Error when deleting strands or xovers

### ISSUE THREAD

**Issue by scholer** [cadnano/cadnano2.5#39]
When trying to delete strands or xovers in dev branch (at 886922fd or 5cccc7e), it is only possible to delete the a strand at the 3p end of an oligo. Anything else throws an error with traceback:

    Traceback (most recent call last):
      File "C:\Users\scholer\Dev\src-repos\cadnano\cadnano2.5\cadnano\gui\views\pathview\pathselection.py", line 135, in keyPressEvent
        self.selectionbox.deleteSelection()
      File "C:\Users\scholer\Dev\src-repos\cadnano\cadnano2.5\cadnano\gui\views\pathview\pathselection.py", line 469, in deleteSelection
        self._item_group.document().deleteSelection()
      File "C:\Users\scholer\Dev\src-repos\cadnano\cadnano2.5\cadnano\document.py", line 334, in deleteSelection
        Part.removeXover(part, strand, strand3p, useUndo)
    AttributeError: type object 'Part' has no attribute 'removeXover'

The issue seems to be exactly the same (and same traceback) whether deleting a strand or an xover.

**Comment by scholer** [comment]
This issue was fixed quite easily by replacing Part with OrigamiPart, see 5cccc7e on my dev branch. (If you want, I can submit a pull request - although my dev branch has a few extra changes, mostly white spaces and formatting changes.)

**Comment by grinner** [comment]
Please PR  the fix in document.py.  Thanks for helping with this.  Let me know any other specific things you'd like seen resolved, clarified and I'll try to work them into my schedule.
