### ISSUE TITLE
random autostaple crash

### ISSUE THREAD

**Issue by sdouglas** [cadnano/cadnano2.5#60]
Got a weird crash when clicking around creating strands in multiple parts. Maybe autoScaf can be triggered on a single helix?

```
Traceback (most recent call last):
  File "./cadnano/gui/views/sliceview/emptyhelixitem.py", line 339, in mouseReleaseEvent
    self.autoScafMidSeam(strands)
  File "./cadnano/gui/views/sliceview/emptyhelixitem.py", line 193, in autoScafMidSeam
    strand2 = vh2.scaffoldStrandSet().getStrand(ss_base_low_idx2)
AttributeError: 'NoneType' object has no attribute 'scaffoldStrandSet'
Abort trap: 6
```

**Comment by sdouglas** [comment]
apparently this is a dupe of #33

**Comment by grinner** [comment]
To fix this, `Part`s need a default name.  can `_properties` in `Part` get updated to have a name?
