### ISSUE TITLE
Editing 'name' property throws exception

### ISSUE THREAD

**Issue by sdouglas** [cadnano/cadnano2.5#66]
Steps to reproduce for virtualhelix name:

1. Create a part, and a vh
2. Select the vh in outlinerview
3. Edit the vh name in propertyview.

Result:
```
outliner <class 'cadnano.gui.views.outlinerview.virtualhelixitem.VirtualHelixItem'> - updateModel
Traceback (most recent call last):
  File "./cadnano/gui/views/outlinerview/outlinertreewidget.py", line 135, in dataChangedSlot
    c_i.updateModel()
  File "./cadnano/gui/views/outlinerview/cnoutlineritem.py", line 53, in updateModel
    if color != cn_model.getProperty('color'):
  File "./cadnano/virtualhelix/virtualhelix.py", line 83, in getProperty
    return self._properties[key]
KeyError: 'color'
Abort trap: 6
```

Steps to reproduce for part name:
1. Create a part
2. Edit the part name in the outlinerview

Result:
```
outliner <class 'cadnano.gui.views.outlinerview.nucleicacidpartitem.NucleicAcidPartItem'> - updateModel
Traceback (most recent call last):
  File "./cadnano/gui/views/propertyview/abstractproppartitem.py", line 29, in partPropertyChangedSlot
    self.setValue(property_key, new_value)
  File "./cadnano/gui/views/propertyview/cnpropertyitem.py", line 87, in setValue
    current_value = p_i.data(VAL_COL, Qt.DisplayRole)
AttributeError: 'str' object has no attribute 'data'
Abort trap: 6
```

**Comment by grinner** [comment]
fixed
