### ISSUE TITLE
pyqt5_check.py: 'module' object has no attribute 'BASE_PREFIX'

### ISSUE THREAD

**Issue by TheBeachLab** [cadnano/cadnano2.5#74]
Hi, I'm having trouble executing the checker under Ubuntu 15.10. This is error message. Any clues?

```bash
irix@hal9000:/opt/cadnano2.5$ python pyqt5_check.py
need to install
OS is Linux or Mac
Traceback (most recent call last):
  File "pyqt5_check.py", line 201, in <module>
    checker()
  File "pyqt5_check.py", line 190, in checker
    pyroot_path = distutils.sysconfig.BASE_PREFIX
AttributeError: 'module' object has no attribute 'BASE_PREFIX'
```

**Comment by grinner** [comment]
Yes this is a symptom of running python 2 and not python 3.  Try running with python3 pyqt5_check.py, or change BASE_PREFIX to PREFIX.  I've made the change in master for you to try.

**Comment by TheBeachLab** [comment]
Thank you @grinner  that solved the problem! now it looks like there is a broken link in the files being downloaded

```bash
irix@hal9000:/opt/cadnano2.5$ python3 pyqt5_check.py 
need to install
OS is Linux or Mac
Building qt5

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/bin/sh: 1: cd: can't cd to qt-everywhere-opensource-src-5.3.2
mkdir: cannot create directory ‘build’: File exists
/bin/sh: 1: ../configure: not found
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
Building pyqt5
--2015-12-10 21:21:36--  http://www.riverbankcomputing.com/static/Downloads/PyQt5/PyQt-gpl-5.4-snapshot-837edec02d98.tar.gz
Resolving www.riverbankcomputing.com (www.riverbankcomputing.com)... 66.151.32.244
Connecting to www.riverbankcomputing.com (www.riverbankcomputing.com)|66.151.32.244|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://riverbankcomputing.com/static/Downloads/PyQt5/PyQt-gpl-5.4-snapshot-837edec02d98.tar.gz [following]
--2015-12-10 21:21:36--  https://riverbankcomputing.com/static/Downloads/PyQt5/PyQt-gpl-5.4-snapshot-837edec02d98.tar.gz
Resolving riverbankcomputing.com (riverbankcomputing.com)... 66.151.32.244
Connecting to riverbankcomputing.com (riverbankcomputing.com)|66.151.32.244|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-10 21:21:37 ERROR 404: Not Found.

tar (child): PyQt-gpl-5.4-snapshot-837edec02d98.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/bin/sh: 1: cd: can't cd to PyQt-gpl-5.4-snapshot-837edec02d98
python: can't open file 'configure.py': [Errno 2] No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
irix@hal9000:/opt/cadnano2.5$
```

**Comment by grinner** [comment]
I see the issue now.  The best version of pyqt5_check.py is in the dev branch.  I'll merge it into master.

**Comment by TheBeachLab** [comment]
Thanks, after the pull I got it!
```bash
irix@hal9000:/opt/cadnano2.5$ sudo python3 pyqt5_check.py
Import success! No need to do anything
```
But then:
```bash
irix@hal9000:/opt/cadnano2.5$ python3 bin/main.py
['bin/main.py']
Traceback (most recent call last):
  File "bin/main.py", line 44, in <module>
    main(sys.argv)
  File "bin/main.py", line 24, in main
    app = initAppWithGui(args)
  File "./cadnano/__init__.py", line 38, in initAppWithGui
    shared_app.finishInit()
  File "./cadnano/cadnanoqt.py", line 63, in finishInit
    from cadnano.gui.controllers.documentcontroller import DocumentController
  File "./cadnano/gui/controllers/documentcontroller.py", line 8, in <module>
    from cadnano.gui.views.documentwindow import DocumentWindow
  File "./cadnano/gui/views/documentwindow.py", line 9, in <module>
    from cadnano.gui.views.pathview.pathrootitem import PathRootItem
  File "./cadnano/gui/views/pathview/pathrootitem.py", line 2, in <module>
    from .partitem import PartItem
  File "./cadnano/gui/views/pathview/partitem.py", line 9, in <module>
    from cadnano.gui.ui.mainwindow.svgbutton import SVGButton
  File "./cadnano/gui/ui/mainwindow/svgbutton.py", line 4, in <module>
    from PyQt5.QtSvg import QSvgRenderer
ImportError: No module named 'PyQt5.QtSvg'
```
So I also had to install the following packages to and now is working:

```bash
sudo apt-get install libqt5webkit5-dev
sudo apt-get install python3-pyqt5.qtsvg
sudo apt-get install python3-pyqt5.qtwebkit
```

MANY THANKS @grinner
