### ISSUE TITLE
Trouble opening cadnano app on Mac OS X 10.10 

### ISSUE THREAD

**Issue by warmtint** [cadnano/cadnano2.5#81]
I am using anaconda for python and I installed the pyqt5 following the instruction.
However everytime I execute the command below, I get the error msg.

(pyqt5)DNAs-Mac-Pro:cadnano2.5 dnaorigami$ python ~/Dev/cadnano2.5/bin/main.py

['/Users/dnaorigami/Dev/cadnano2.5/bin/main.py']
('the doc', <cadnano.document.Document object at 0x10c773938>)
Traceback (most recent call last):
  File "/Users/dnaorigami/Dev/cadnano2.5/bin/main.py", line 44, in <module>
    main(sys.argv)
  File "/Users/dnaorigami/Dev/cadnano2.5/bin/main.py", line 24, in main
    app = initAppWithGui(args)
  File "./cadnano/__init__.py", line 38, in initAppWithGui
    shared_app.finishInit()
  File "./cadnano/cadnanoqt.py", line 66, in finishInit
    self.d = self.newDocument(base_doc=doc)
  File "./cadnano/cadnanoqt.py", line 138, in newDocument
    dc = DocumentController(base_doc)
  File "./cadnano/gui/controllers/documentcontroller.py", line 48, in __init__
    self._initWindow()
  File "./cadnano/gui/controllers/documentcontroller.py", line 53, in _initWindow
    self.win = DocumentWindow(doc_ctrlr=self)
  File "./cadnano/gui/views/documentwindow.py", line 41, in __init__
    self.setupUi(self)
  File "./cadnano/gui/ui/mainwindow/ui_mainwindow.py", line 24, in setupUi
    MainWindow.setUnifiedTitleAndToolBarOnMac(True)
AttributeError: 'DocumentWindow' object has no attribute 'setUnifiedTitleAndToolBarOnMac'

**Comment by scholer** [comment]
Hi Warmtint,
From your prompt I understand the following:
(1) You are on the dnapart branch, and (2) you've installed pyqt with anaconda. Let me know of these assumptions are wrong.
Nick is currently doing intense work on the dnapart branch, and I don't think this branch is ready for public consumption yet. I'm using the "dev" branch for my everyday work. The official dev branch has some bugs, but I've fixed the ones I've encountered. I can push the fixes to my repo at https://github.com/scholer/cadnano2.5 if you want to give that branch a go.
--Rasmus

**Comment by grinner** [comment]
This is fixed, but I will close this issue on the new release
