### ISSUE TITLE
import fails with files containing insertions (dev branch)

### ISSUE THREAD

**Issue by sdouglas** [cadnano/cadnano2.5#82]
Steps to reproduce: attempt to open a file (e.g. exported from cadnano1) that contains insertions.

Traceback:

```
partAddedSlot:  <HoneycombPart 2072> HoneycombPart
Traceback (most recent call last):
  File "./cadnano/gui/controllers/documentcontroller.py", line 601, in openAfterMaybeSaveCallback
    decodeFile(fname, document=self._document)
  File "./cadnano/fileio/nnodecode.py", line 18, in decodeFile
    decode(document, nno_dict)
  File "./cadnano/fileio/nnodecode.py", line 238, in decode
    strand.addInsertion(base_idx, sum_of_insert_skip, use_undostack=False)
AttributeError: 'NoneType' object has no attribute 'addInsertion
```

**Comment by sdouglas** [comment]
![1](https://cloud.githubusercontent.com/assets/45583/14685863/3c91bfd4-06eb-11e6-90dc-caf1155bb473.jpg)

**Comment by grinner** [comment]
When do you encounter this issue happening?

**Comment by sdouglas** [comment]
This was reported by someone a while back and the problem was with their file. This design will fail to import: [stray_skip.json.zip](https://github.com/cadnano/cadnano2.5/files/1682774/stray_skip.json.zip)

It's now a matter of failing gracefully by not assuming insertions/skips are over a strand, since legacy versions do allow you to resize a strand in a way that leaves an orphan insertion/skip.

**Comment by grinner** [comment]
Therefore we should have the decoder enforce that insertions and skips exist on a strand?

**Comment by sdouglas** [comment]
I'd like to delay file validation if we can, or just do a lightweight version that checks if the basic dict keys are present. From a user standpoint, if we just ignore orphan inserts/skips maybe print a warning, it's still possible to open old cn1 files where someone accidentally created these. Also, for development/debugging it's often very informative to see what the GUI does with invalid file input.
