### ISSUE TITLE
Paint tool crashes when attempting rubber-band selection

### ISSUE THREAD

**Issue by sdouglas** [cadnano/cadnano2.5#92]
<img width="316" alt="005" src="https://cloud.githubusercontent.com/assets/45583/20405407/c22a956c-acbd-11e6-9c40-6f9efc5511f1.png">

**Steps to reproduce:** 

1. Create some oligos
2. Activate Paint tool
3. Mouse-press in pathview outside the part, and drag to get rubber band selection box. 
4. Proceed to try to select an oligo in order to change its color.

**If your selection first encounters an endpoint:**

```
Traceback (most recent call last):
  File "./cadnano/gui/views/pathview/strand/endpointitem.py", line 493, in itemChange
    self.paintToolMousePress(None, None, None)
  File "./cadnano/gui/views/pathview/strand/endpointitem.py", line 317, in paintToolMousePress
    if modifiers & Qt.ShiftModifier:
TypeError: unsupported operand type(s) for &: 'NoneType' and 'KeyboardModifier'
Abort trap: 6
```

**If you first encounter an internal strand segment between endpoints:**

```
Traceback (most recent call last):
  File "./cadnano/gui/views/pathview/strand/stranditem.py", line 749, in itemChange
    self.paintToolMousePress(None, None)
  File "./cadnano/gui/views/pathview/strand/stranditem.py", line 594, in paintToolMousePress
    color = m_strand.color()
AttributeError: 'Strand' object has no attribute 'color'
Abort trap: 6
```

**Comment by grinner** [comment]
Seems like this is fixed
